### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by tmilewski** [omniauth/omniauth-instagram#28]
@ropiku What are your thoughts on moving this over to the [omniauth organization](https://github.com/omniauth) so that this gem can be appropriately maintained moving forward.

I'm happy to get that process going.

**Comment by ropiku** [comment]
I'm very happy to get someone to maintain this. Feel free to contact me directly with next steps.

**Comment by tmilewski** [comment]
@ropiku You'll just need to make me an admin of this repository.

@bufferoverflow Would you mind bumping me up to an owner in the omniauth org so that I can get this transferred? I'm going to work to get `omniauth-github` transferred as well.

**Comment by ropiku** [comment]
@tmilewski I can initiate the transfer and the new owner has to approve the transfer in 1 day. Once you are an owner in omniauth org I can send it.

**Comment by tmilewski** [comment]
Hey, just wanted to ping you guys again to get bumped up to an owner for the Omniauth org. I'll able to bring a bunch of provider gems under the organization's umbrella.

/cc @bufferoverflow @danwiding @md5 @sferik @supernova32

**Comment by md5** [comment]
@tmilewski I think a better approach would be to make one of the existing owners of @omniauth an outside contributor with admin privileges on each repo. That will let one of us do the transfers. I think we'll also need a team for each provider gem. I'm happy to facilitate the transfers, but I won't have time today. Tomorrow will work though.

**Comment by md5** [comment]
Actually, I see now that you're already on the Omniauth maintainers team. In that case, I think it's fine to make you an owner.

**Comment by md5** [comment]
@tmilewski I made you an owner. Please make a separate team for each provider gem you transfer :+1:

**Comment by tmilewski** [comment]
@md5 Can do. Thanks a lot!

**Comment by tmilewski** [comment]
@ropiku Whenever you have a minute to initiate the transfer, have at it! I'll be able to approve from the other end. Thanks!

**Comment by bufferoverflow** [comment]
I saw this too late... @md5 @tmilewski great to see the idea of omniaouth organization growing

**Comment by ropiku** [comment]
@tmilewski I cannot transfer it to `omniauth` as I don't have repo create permissions. I sent a request to your personal account. Hope then you could transfer it to the omniauth org again and it will keep the redirects.

**Comment by md5** [comment]
I haven't transferred a repo in a while, but if I recall, the person doing the transfer needs to have admin rights on the source repo and the ability to create respositories in the target organization. Adding @tmilewski as an outside contributor with admin rights should allow the transfer to happen.

**Comment by bufferoverflow** [comment]
@ropiku I made you an owner of omniauth, so you can initiate the transfer

**Comment by ropiku** [comment]
@bufferoverflow Done. Thanks !

**Comment by md5** [comment]
@bufferoverflow I think we need to be pretty conservative about who we make owners of the repo, particularly given the fact that OmniAuth is a security-related gem. It's fine for @tmilewski to be an owner, given that he's a maintainer of `omniauth`, but my understanding is that @ropiku is no longer going to maintain even `omniauth-saml`. I really don't think we should be adding people to the organization with elevated privileges just for the sake of expediency.

Please let me know if I've misunderstood the situation or @ropiku's role in things, but I would like to change his status to just be a member and part of the "omniauth-instagram maintainers" team.

**Comment by ropiku** [comment]
@bufferoverflow I only needed to be an admin temporarily, please remove me. Even then I think I could've migrated it to your personal account then to `omniauth` org.

**Comment by bufferoverflow** [comment]
@md5 I made @ropiku a member

**Comment by ropiku** [comment]
Let me know who should get Gem pushing permissions.

**Comment by tmilewski** [comment]
@ropiku I'm happy to take that over.
