### ISSUE TITLE
Default devise config problem - Instagram is not returning email anymore

### ISSUE THREAD

**Issue by dimartiro** [omniauth/omniauth-instagram#32]
If we see the [instagram doc](https://www.instagram.com/developer/authentication/), they are not returning the user email anymore, it causes problems with the default devise configuration.

https://github.com/omniauth/omniauth-instagram/blob/bac44813eb2d551bca4f400401cf0cdf4f651a5a/lib/omniauth/strategies/instagram.rb#L28

**Comment by tmilewski** [comment]
Thanks for the heads up! Updated @ v1.2.0.
